In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [3]:
type(l)

list

In [4]:
arr = np.array(l)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(5,)

In [8]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]

In [10]:
arr1= np.array([lst1,lst2,lst3])

In [11]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [12]:
arr1.shape

(3, 5)

In [15]:
arr[4] 

5

In [16]:
arr1[:2,2:]

array([[3, 4, 5],
       [4, 5, 6]])

In [17]:
arr1[-1]

array([3, 4, 5, 6, 7])

In [18]:
arr1[:-1]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [19]:
arr[::-2]

array([5, 3, 1])

In [20]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [23]:
arr1[:,1]

array([2, 3, 4])

In [28]:
arr1[:,[0,4]]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [29]:
arr

array([1, 2, 3, 4, 5])

In [30]:
arr<2

array([ True, False, False, False, False])

In [31]:
arr[arr<2]

array([1])

In [32]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [33]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [34]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.random.randint(10,50)

44

In [41]:
np.random.randint(10,50,4)

array([44, 21, 42, 38])

In [44]:
np.random.randint(10,50,4).reshape(2,2)

array([[40, 41],
       [12, 48]])

In [45]:
## data[:, ['Column Name1','Column Name2']]

arr1[:, [3,4]]

array([[4, 5],
       [5, 6],
       [6, 7]])